<?php
include('../source/api.php');
require("../source/phpmailer/PHPMailerAutoload.php");

$currDate = date('d-m-Y');
$currDate = DateTime::createFromFormat('d-m-Y', $currDate);
$pullLease = "SELECT * FROM `leased`";
$leases = $db->query($pullLease);

while ($currLease = $leases->fetchObject()){
	$dueDate = DateTime::createFromFormat('d/m/Y', $currLease->date);
	$diff = $dueDate->diff($currDate);
	//print $diff->format('%a');
	//echo $currLease->serialNumber . ' : '.  $diff->format('%a') . " - " . $diff->format('%d') . "<br/>";
	if ($diff->format('%a') == 31 OR $diff->format('%a') == 14 OR $diff->format('%a') == 24 OR $diff->format('%a') == 7){
		if ($currLease->owner != "" AND isset($currLease->owner)){
			$owner = $currLease->owner;
		}else{
			$owner = "No User";
		}
		$dueDevices[$currLease->serialNumber] = [$owner, $currLease->assocList, $currLease->date];
		if ($currLease->owner != "" AND isset($currLease->owner)){
			$msg = "The lease on your device is about to expire.\n
			Please backup all of your files from your computer, and return it to Shayna A.S.A.P.\n
			It must be returned to the supplier by " . $currLease->date . ".\n
			\n
			\n
			\n
			\n
			\n
			This is a automated message. Do not reply. Generated by LeaseManage &copy;\n";

			//sendMail("ebs@spotswoodcollege.school.nz", $msg);
			sendMail($currLease->owner . "@" . $homeUrl, $msg);
		}
	}
}

$adminMsg = "The following devices are due to be returned within the next month:\n
";
foreach ($dueDevices as $key => $value) { 
	$adminMsg .= $key . "     " . $dueDevices[$key][0] . "       ". $dueDevices[$key][1] . "      ". $dueDevices[$key][2] . "\n";
} 
$adminMsg .= "\n This is a automated message. Do not reply. \nGenerated by LeaseManage. Copyright 2015\n";


//sendMail("ebs@spotswoodcollege.school.nz", $adminMsg);
sendMail("cla@spotswoodcollege.school.nz", $adminMsg);
sendMail("helper@spotswoodcollege.school.nz", $adminMsg);
?>